### ISSUE TITLE
Branch libuv-v1.48.0 fails in MSVC due to 'spawn_no_ext'  test failing

### ISSUE THREAD

**Issue by ibc** [ibc/wrapdb#1]
https://github.com/ibc/wrapdb/actions/runs/8112349589/job/22173393748

```
  not ok 263 - spawn_no_ext
  # exit code -1073740791
  # Output from process `spawn_no_ext`:
  # Assertion failed in ../subprojects/libuv-v1.48.0/test/test-spawn.c on line 1412: `uv_spawn(uv_default_loop(), &process, &options) == 0` (-4058 == 0)
```

**Comment by ibc** [comment]
@saghul can you help please?

I'm trying to update libuv to latest 1.48 version in Meson WrapDB, here the PR https://github.com/mesonbuild/wrapdb/pull/1432 which corresponds to branch [libuv-v1.48.0](https://github.com/ibc/wrapdb/tree/libuv-v1.48.0) in this fork of `wrapdb` project.

I checked all the diff between 1.47.0 and 1.48.0 in libuv and I don't think there is anything missing in my changes in `meson.build`. I'm worried that "perhaps" there is an issue affecting certain Windows+MSVC environments that do not happen in libuv CI.

**Comment by saghul** [comment]
The error is ENOENT on Windows: https://github.com/libuv/libuv/blob/a7c44d674833e8dec66b8730b5635fcad0f81162/include/uv/errno.h#L248

Perhaps the working directory is different on that build system?

**Comment by saghul** [comment]
At any rate, I'm 99.87% certain there are no compiler shenanigans to worry about.

**Comment by ibc** [comment]
> Perhaps the working directory is different on that build system?

This doesn't tell me much. How is that error related to the working directory and why should that stop passing test on Windows from 1.47 to 1.48?

**Comment by saghul** [comment]
Good questions :-)

That's a new test actually, coming from https://github.com/libuv/libuv/commit/3f7191e5c27a0e1852fe046a5ec0512a47e4a409

**Comment by ibc** [comment]
Hell, I didn't port those changes in CMakeLists to meson.build because I don't know how to do it.

**Comment by ibc** [comment]
@saghul maybe you know how to port this block in `CMakeLists.txt` to `meson.build`?

https://github.com/libuv/libuv/commit/3f7191e5c27a0e1852fe046a5ec0512a47e4a409

```make
if(WIN32)
    add_custom_command(TARGET uv_run_tests POST_BUILD
                       COMMAND "${CMAKE_COMMAND}" -E copy
                       "$<TARGET_FILE:uv_run_tests>"
                       "$<TARGET_FILE_DIR:uv_run_tests>/uv_run_tests_no_ext")
endif()
```

**Comment by ibc** [comment]
I've found this https://mesonbuild.com/Fs-module.html#copyfile (https://github.com/mesonbuild/meson/pull/10042) but it's for copying files from the source directory to the build directory. In our case we need to copy an executable in the build directory (`uv_run_test`, which may have extension in Windows) to another executable `uv_run_tests_no_ext`, without extension) in the same build directory.

**UPDATE:** Ok, I cannot find absolutely anything in Meson land that makes it possible to copy a file from build directory to same build directory.

**Comment by saghul** [comment]
Perhaps we can just add another target that builds the test suite with the new name too? I'd assume meson would be smart enough to reuse all the objects and just relink...

**Comment by ibc** [comment]
> Perhaps we can just add another target that builds the test suite with the new name too? I'd assume meson would be smart enough to reuse all the objects and just relink...

I thought about that, but I'm afraid Meson will create that executable with .exe or .cmd extension in Windows, and we need it without extension.

**Comment by saghul** [comment]
I'd imagine there is a way to control that, isn't there?

**Comment by ibc** [comment]
> I'd imagine there is a way to control that, isn't there?

I'd need to become a Meson expert to answer that.

**Comment by ibc** [comment]
@nazar-pc, maybe you know?

**Comment by ibc** [comment]
I'm trying this: https://github.com/mesonbuild/wrapdb/pull/1432/commits/0c625e7e32258a493fccb6017fcd0f9ea2678788

**Comment by ibc** [comment]
Ok, so of course `name_suffix: void` is not a valid thing. Then I've tried with `name_suffix: ''` and got this error:

```
subprojects\libuv-v1.48.0\meson.build:693:4: ERROR: executable keyword argument "name_suffix" must not be
a empty string. An empty array may be passed if you want Meson to use the default behavior.
```

Now trying with `name_suffix: None` which also fails:

```
subprojects\libuv-v1.48.0\meson.build:699:19: ERROR: Unknown variable "None".
```

So no idea. `executable` in meson.build allows `name_suffix` option but there is no way to tell it "DO NOT ADD IT":
https://mesonbuild.com/Reference-manual_functions.html#executable

**Comment by ibc** [comment]
Hack attempt:

`name_suffix: ' '` (this is, a string containing a single space).

Will not work because, of course, meson is appending the dot anyway:

> [775/776] Compiling C object "subprojects/libuv-v1.48.0/uv_run_tests_a_no_ext.

https://github.com/mesonbuild/meson/blob/master/mesonbuild/build.py#L634

**Comment by ibc** [comment]
> Hack attempt:
> 
> `name_suffix: ' '` (this is, a string containing a single space).
> 
> Will not work because, of course, meson is appending the dot anyway:
> 
> > [775/776] Compiling C object "subprojects/libuv-v1.48.0/uv_run_tests_a_no_ext.

However it works: https://github.com/ibc/wrapdb/actions/runs/8144283789/job/22258065595

**Comment by saghul** [comment]
LoL

**Comment by ibc** [comment]
But it doesn't make any sense so I'm trying other things.

**Comment by ibc** [comment]
This is hell. I cannot spend more time on this. It's been already 48 hours.

**Comment by ibc** [comment]
Ok, so problem I have is this:

```
----- full_path: D:\a\wrapdb\wrapdb\_build\subprojects\libuv-v1.48.0\uv_run_tests.exe
  ----- os.getenv('MESON_BUILD_ROOT'): D:\a\wrapdb\wrapdb\_build
  ----- os.getenv('MESON_SUBDIR'): subprojects\libuv-v1.48.0
  ----- build_dir: D:\a\wrapdb\wrapdb\_build\subprojects\libuv-v1.48.0
  ----- os.listdir(build_dir): []
  
  --- stderr ---
  Traceback (most recent call last):
    File "D:\a\wrapdb\wrapdb\subprojects\libuv-v1.48.0\copy_file_in_build_dir.py", line 26, in <module>
      shutil.copyfile(input_path, output_path)
    File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\shutil.py", line 264, in copyfile
      with open(src, 'rb') as fsrc:
  FileNotFoundError: [Errno 2] No such file or directory: 'D:\\a\\wrapdb\\wrapdb\\_build\\subprojects\\libuv-v1.48.0\\uv_run_tests.exe'
```

In `meson.build`:

```meson
  libuv_test_exe = executable(
    'uv_run_tests',
    libuv_test_src,
    dependencies: [libuv_dep, libuv_test_deps],
    c_args: libuv_test_cargs,
    link_args: libuv_test_lflags,
  )
  # we need to copy the executable without extension (needed for a test in libuv)
  if win32
    copy_file_in_build_dir = find_program('copy_file_in_build_dir.py')
    run_command(
      copy_file_in_build_dir,
      libuv_test_exe.full_path(),
      'uv_run_tests.exe',
      'uv_run_tests_no_ext',
      check: true
    )
  endif
```

So the problem is that the `libuv_test_exe = executable(...)` task completes **before** the executable `D:\a\wrapdb\wrapdb\_build\subprojects\libuv-v1.48.0\uv_run_tests.exe` is generated, and hence the copy command after it fails because such a file does NOT yet exist.

**Comment by nazar-pc** [comment]
`meson.build` is more declarative than imperative, so I can see how `run_command` runs immediately and `executable` just defines executable to be compiled later.

Did you find out why is it necessary to rename executable in the first place though?

**Comment by ibc** [comment]
> Did you find out why is it necessary to rename executable in the first place though?

To run a libuv test that literally spawns an executable in the build directory with no extension: https://github.com/libuv/libuv/commit/3f7191e5c27a0e1852fe046a5ec0512a47e4a409#diff-11212f8e475803e54d36f9fdc6730ba9f8d8af989c6bf33facc49d25260eb99b

The executable is the test executable itself but the test in libuv uses it without extension.

**Comment by nazar-pc** [comment]
Ask in Meson's Matrix chat what to do with this. I think even skipping this test for now and just leaving TODO might be fine.

**Comment by ibc** [comment]
I don't know how to skip that test. It's not a separate file but a new test in an existing test file: https://github.com/libuv/libuv/commit/3f7191e5c27a0e1852fe046a5ec0512a47e4a409#diff-474ff289edd74587d2dbcd1e8792169a7a3d89b8c582f8715aadf83da67800f5R1402

**Comment by ibc** [comment]
I've found this (see custom_target() usage) but I'm not sure I understand how it works:

https://stackoverflow.com/questions/65390930/how-can-i-run-a-custom-command-at-build-time-in-meson

**Comment by ibc** [comment]
> I've found this (see custom_target() usage) but I'm not sure I understand how it works:
> 
> https://stackoverflow.com/questions/65390930/how-can-i-run-a-custom-command-at-build-time-in-meson

Nothing. Same problem: https://github.com/mesonbuild/wrapdb/pull/1432#issuecomment-1977305175

**Comment by ibc** [comment]
@saghul do you know if it's possible to run libuv tests by excluding some specific tests? I don't see how, probably it's not possible at all. I just want to exclude the new 2 tests added in the infamous commit https://github.com/libuv/libuv/commit/3f7191e5c27a0e1852fe046a5ec0512a47e4a409#diff-474ff289edd74587d2dbcd1e8792169a7a3d89b8c582f8715aadf83da67800f5R1402 in `test-spawn.c`.

**Comment by saghul** [comment]
Alas there is no way...

**Comment by nazar-pc** [comment]
What is possible and should in theory work is creating a symlink with desired name pointing to the other file. Even though file doesn't exist during symlink creation, it will exist when test runs and that is all that matters.

**Comment by ibc** [comment]
> What is possible and should in theory work is creating a symlink with desired name pointing to the other file. Even though file doesn't exist during symlink creation, it will exist when test runs and that is all that matters.

Interesting. Could you tell me how to create a symlink in Windows? (I know you love Windows).

The custom script I am using to copy the file (which now should symlink it) is this:

```py
#!/usr/bin/env python3

import os, sys, shutil

file_in = sys.argv[1]
file_out = sys.argv[2]
build_dir = os.path.join(
    os.getenv('MESON_BUILD_ROOT'),
    os.getenv('MESON_SUBDIR'))

# for debugging
print(f"----- build_dir = {build_dir}")
print(f"----- os.listdir(build_dir): {os.listdir(build_dir)}")

# get absolute input and output paths
input_path = os.path.join(build_dir, file_in)
output_path = os.path.join(build_dir, file_out)

# copy the file
shutil.copyfile(input_path, output_path)
```

And I run it as follows in `meson.build`:

```meson
    copy_file_in_build_dir = find_program('copy_file_in_build_dir.py')
    run_command(
      copy_file_in_build_dir,
      'uv_run_tests.exe',
      'uv_run_tests_no_ext',
      check: true
    )
```

**Comment by ibc** [comment]
Ignore, this is Python. Python will know probably.

**Comment by ibc** [comment]
Done here: https://github.com/mesonbuild/wrapdb/pull/1432/commits/bd4607548c31cac62b71a6c4986c703e924b19db
CI running here: https://github.com/ibc/wrapdb/actions/runs/8153471340/job/22284926392

**Comment by ibc** [comment]
OMG it's working!

**Comment by ibc** [comment]
Thanks @nazar-pc !

**Comment by saghul** [comment]
🎉
